### ISSUE TITLE
Artifacts module implemention

### ISSUE THREAD

**Issue by balsulami** [NickChapman/RequestNetwork.py#6]
This module in RequestNetwork.js is made of JSON files. I don't have experience with Javascript. Should I convert each JSON into static class in Python or write a python script that loads those JSON files into Python object dynamically? 

I'm planning to contribute to this project. I just need a small guidance. 

Thanks

**Comment by NickChapman** [comment]
I have already implemented a class which will load the JSON files and allow you to interact with them as dictionaries.

**Comment by balsulami** [comment]
I see what you were trying to do. So it's the second option. 

Also, The JSON files are empty. Is there a reason why you didn't copy the same files from the JS project? I could do that if there is no reason. 

Thanks

**Comment by NickChapman** [comment]
Only reason is that I'm waiting to see if Vincent can put the artifacts into their own repo that we can just include as a submodule. If you want to copy them in for now that's fine.

**Comment by balsulami** [comment]
I see. I will copy them for now and we can change them later. Because It helped me testing and understanding the code a little bit. Thanks
